title: Summit
baseURL: /
params:
  layout_style: grid
  palette: black
  header:
    title: Summit
    logo_img: ''
    has_nav: true
  footer:
    content: '&copy; 2023. All rights reserved.'
    links:
      - text: SUMMIT
        url: /
        new_window: true
    has_social: true
menu:
  main: []
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
