title: Stackbit Ampersand Theme
baseURL: /
params:
  layout_style: grid
  palette: black
  header:
    title: Summit
    logo_img: ''
    has_nav: true
  footer:
    content: '&copy; All rights reserved.'
    links:
      - text: Summit Enterprises
        url: /
        new_window: true
    has_social: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
